Add CLO mainnet and testnet RPC
kvhnuke/etherwallet pull request #1770
Opened 2018-04-14 20:29 UTC by yograterol

- Add RPC node of https://callisto.network/ for Testnet
- Add RPC node of https://callisto.network/ for Mainnet

2018-04-15 05:29 UTC, akx20000a commented on app/scripts/nodes.js
> +    },
This gives me a syntax error, }, -> }

2018-04-15 05:30 UTC, akx20000a commented on app/scripts/nodes.js
> +    },
Syntax error } to }, will be fine 😄

2018-04-15 05:30 UTC, ghost requested changes

2018-04-15 05:30 UTC, akx20000a commented on app/scripts/nodes.js
> +    },
Syntax error } to }, will be fine 😄

2018-04-16 22:05 UTC, yograterol commented
@akx20000a thanks!

2018-04-18 00:39 UTC, ghost approved these changes
ACK

2018-04-27 13:58 UTC, yograterol commented
ACK

2018-04-30 23:07 UTC, gamalielhere commented
@yograterol Can you fix the conflict? I'll merge it afterwards

2018-04-30 23:07 UTC, gamalielhere approved these changes

2018-05-03 13:29 UTC, yograterol commented
@gamalielhere Rebase done.

2018-05-03 17:11 UTC, merged