update Korean translations
kvhnuke/etherwallet pull request #1875
Opened 2018-05-29 18:42 UTC by hackmod

*Please do not merge it*

## TODO
- translate more messages

2018-05-30 11:56 UTC, ghost approved these changes
ACK

2018-05-30 16:20 UTC, allsoft777 commented on app/scripts/translations/ko.js
>  DOMAIN_Finish_1                 :  'Not related to that auction',
경매와 관련이 없습니다.

2018-05-31 08:57 UTC, akx20000a commented
저희 ETSC 개발팀도 이번 번역 PR 에 참여하시는 모든 기여자 분들에게 일인당 5000 ETSC를 보상으로 지급하려고 합니다. 화이팅!

2018-05-31 09:00 UTC, chung0011 commented on app/scripts/translations/ko.js
> -GEN_Warning_1                   :  '**Do not lose it!** It cannot be recovered if you lose it.',
'**절대 잃어버리지 마세요!** 당신이 그것을 잃어버린다면, 복구할 수 없습니다.'

2018-05-31 09:04 UTC, chung0011 commented on app/scripts/translations/ko.js
> +GEN_Warning_1                   :  '**잃어버리지 마세요!** 잊어버리면 복구하지 못합니다.',
'**절대 잃어버리지 마세요!** 잃어버리면 복구하지 못합니다.',

2018-05-31 13:06 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Warning_1                   :  '**잃어버리지 마세요!** 잊어버리면 복구하지 못합니다.',
'**키를 분실하지 마세요!** 키를 분실하면 지갑을 복구할 수 없습니다.',

2018-05-31 13:18 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_0                      :  '지갑이 이미 다른 곳에 있나요?',
'지갑을 이미 보유하고 계신가요?',

> Ledger / TREZOR / Digital Bitbox / Secalot/ MetaMask / Jaxx / imToken 등의 서비스를 이용해 이미 지갑을 만든 상태인지 묻는 질문입니다.

2018-05-31 13:23 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_MetaMask               :  '쉽습니다! 키는 MetaMask에 보존되고 피싱 사이트에 노출 안됩니다. 지금 써보세요.',
'매우 간단합니다! 키는 피싱 사이트가 아니라 MetaMask에 보존됩니다. 지금 연결해보세요.',

- 해당 문구를 확인할 수 있는 url: https://www.myetherwallet.com/

2018-05-31 13:50 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Warning_2                   :  '**공유하지 마세요!** 이 파일을 잘못된/피싱 사이트에서 사용하면 자금을 도난당할 수 있습니다.',
소스 코드를 봐서는 Save your Keystore File 과 관련된 경고문처럼 보이네요. this file = Keystore file. (확인부탁드립니다.)

'**Keystore 파일을 공유하지 마세요!**  악의적인/피싱 사이트에서 이 파일을 사용하면 여러분의 자금을 도난당할 수 있습니다.',

2018-05-31 13:54 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Warning_3                   :  '**백업하세요!** 이는 언젠게 수백만 달러의 가치를 가지게 될 수 있으니 보존하세요.',
소스 코드를 봐서는 Save your Keystore File 과 관련된 경고문처럼 보이네요. this file = Keystore file. (확인부탁드립니다.)

'**백업해두세요!** 여러분의 자산이 언젠가는 수 백만 달러의 가치를 될 수 있으니 이 파일을 안전하게 관리하세요.',

2018-05-31 14:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +CONTRACT_Helper_1               :  '주소를 당신의 Multisig 컨트랙트 주소로 변경하세요.',
'당신이 소유한 다중 서명(Multisig) 계약 주소로 주소를 변경하세요.',

Multisig는 다중 서명으로 번역하는 것이 좋을지 Multisig로 유지하는게 좋을지 의견을 정하는게 좋을 것 같네요.

2018-05-31 14:06 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GAS_Price_3                     : '고속',
AF는 무엇을 의미하나요?

2018-05-31 14:13 UTC, dakeshi commented on app/scripts/translations/ko.js
> +CONTRACT_Warning_1              :  '**컨트랙트를 배포**하려고 합니다.',
'당신은 **계약을 배포**하려고 합니다. ',

2018-05-31 14:15 UTC, dakeshi commented on app/scripts/translations/ko.js
> +CONTRACT_Warning_2              :  '이는 다음 네트웨크를 통해 배포됩니다:',
'계약은 아래 네트워크로 배포됩니다:',

2018-05-31 14:17 UTC, dakeshi commented on app/scripts/translations/ko.js
> +CONTRACT_Warning_3              :  '**컨트랙트의 함수를 실행**하려고 합니다.',
'당신은 **계약에 있는 함수를 실행**하려고 합니다.',

2018-05-31 14:20 UTC, dakeshi commented on app/scripts/translations/ko.js
> +SEND_ViewOnly                   :  '당신의 주소만 가지고는 전송할 수 없습니다. 여러 옵션중 한가지를 사용할 수 있으려면 지갑을 풀어주어야 합니다.',
'당신의 주소만 가지고는 전송할 수 없습니다. 전송을 위해 지갑 잠금을 해제할 수 있는 여러 옵션 중 하나를 사용해야 합니다.',

2018-05-31 14:24 UTC, dakeshi commented on app/scripts/translations/ko.js
> +SEND_CustomAddrMsg              :  '이에 대한 메시지',
'아래 트랜잭션과 관련된 메시지',

> customGasMsg와 관련된 내용으로 보이네요. sendTx-content.tpl파일에서 a message regarding 하단에 {{tx.to}} 가 위치하기 때문에 위와 같이 번역했습니다.

2018-05-31 14:25 UTC, dakeshi commented on app/scripts/translations/ko.js
> +SWAP_Warning_1                  :  '경고! 스왑을 완료하기위한 자금이 충분하지 않습니다.',
'경고! 당신은 이 교환을 완료할 수 있는 충분한 자금이 없습니다.',

2018-05-31 14:26 UTC, dakeshi commented on app/scripts/translations/ko.js
> +SWAP_Warning_2                  :  '지갑에 자금을 더 넣거나 다른 지갑으로 접속하세요.',
'지갑에 자금을 추가하거나 다른 지갑을 사용해 시도해보세요.',

2018-05-31 14:35 UTC, dakeshi reviewed
이상하게 add single comment 만 가지고는 아래까지 진행이 안되네요. submit review  하고 이어서 리뷰 진행합니다.

2018-05-31 14:44 UTC, dakeshi reviewed
새로운 커밋이 생산되서 리뷰 제출합니다. 이어서 리뷰 진행합니다.

2018-05-31 14:44 UTC, dakeshi commented on app/scripts/translations/ko.js
> +X_HelpfulLinks                  :  '유용한 링크 및 FAQ',
'도움말 링크 및 자주 묻는 질문',

2018-05-31 14:44 UTC, dakeshi commented on app/scripts/translations/ko.js
> +X_HelpfulLinks_1                :  '지갑 조작 방법',
'당신의 지갑에 접근하는 방법',

2018-05-31 14:44 UTC, dakeshi commented on app/scripts/translations/ko.js
> +X_HelpfulLinks_2                :  '개인 키를 잃었을 경우',
'개인 키를 분실했습니다',

2018-05-31 14:44 UTC, dakeshi commented on app/scripts/translations/ko.js
> +X_HelpfulLinks_3                :  '개인 키로 다른 주소를 여는 경우',
'내 개인 키로 다른 주소를 열었습니다',

2018-05-31 14:51 UTC, hackmod commented
@dakeshi // 수고하셨습니다~
- 컨트랙트는 "계약"으로 번역을 하지 않고 그대로 쓰더군요. 일반적인 계약이 아닌 프로그래밍된 계약이라고 생각해서 그대로 쓰는 듯 합니다. 이 부분은 시간이 해결해주기 전까지는 "컨트랙트"로 두는게 나을 것 같네요.

- Multisig역시 멀티시그라고 그냥 쓰는군요. 일단 몇개 안되니 다중서명(Multisig)라고 고쳐썼습니다.

rebase 했다가 일단 원상복구시켜서 반영이 되었는지 보이게끔 하였습니다~

2018-05-31 14:57 UTC, dakeshi commented
@hackmod 안녕하세요.
-  번역 기준은 https://github.com/ethereum/wiki/wiki/%5BKorean%5D-White-Paper 문서를 참고로 진행했는데 해당 번역에서도 컨트랙트와 계약을 혼용해서 번역된 측면이 있습니다. 대부분의 매체에서 스마트 계약으로 번역되었기 때문에 contract를 `계약`으로 번역했습니다. 
- 다중 서명의 경우도 비슷한 경우입니다.

혹시 기준으로 삼고 있는 번역 문서가 있나요? 참고해서 반영하도록 하겠습니다.

2018-05-31 15:02 UTC, hackmod commented
위에 쓴 대로 컨트랙트와 계약은 혼용 상태입니다. 다중서명도 비슷하다고 보고요. 번역에 대한 토론이 활발하지 않은 관계로, 일단은 기존의 @coinkorea 공동 번역의 의도대로 두었습니다. 다중서명(Multisig)은 병기했습니다. 당분간 계약(컨트랙트) 병기를 하는 것도 방법이겠네요. 어디까지나 번역 토론을 하는 자리는 아니므로 여지는 남겨둡니다.

2018-05-31 15:41 UTC, dakeshi reviewed
1차 리뷰는 여기까지 진행합니다. 시간날 때 2차 리뷰 이어서 진행하겠습니다.

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +X_HelpfulLinks_4                :  'MyEtherWallet으로부터 지갑 이전',
'MyEtherWallet으로/에서 지갑 옮기기',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_bid_0                    :  '현재 입찰가가 가장 높으며 경매에서 이기고 있습니다. 원한다면 더 높은 가격으로 입찰할 수 있지만, 경매 마감 시간이 24시간 지연됩니다.',
'가장 높은 매수호가를 제시했기 때문에 현재 이 경매의 승자는 당신입니다. 원한다면 더 높은 매수호가를 제시할 수 있지만, 그렇게 하면 경매 마감 시간이 24시간 지연됩니다.',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_bid_1                    :  '입찰 최저가',
'최소 매수호가',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_bid_3                    :  '24시간 이내에 더 높은 입찰을 하지 않으면 도메인에 당첨됩니다.',
'다음 24시간 이내에 더 높은 매수호가 주문이 없다면 당신이 도메인을 낙찰받게 될 것입니다.',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_bid_4                    :  '도메인의 잠긴 값은 다음과 같습니다.',
'도메인에 묶여있는(locked) 가치는 다음과 같습니다.',

> locked in value를 말하는 것 같네요. 보호예수조치같은.

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_bid_5                    :  '판매의 일부로 이 공탁금액을 받게 되지만, 이름을 개방하지 않으면 받을 수 없습니다.',
'판매의 일부로 이 가치를 지닌 증서를 받지만 이름을 풀어주기 전까지는 이를 청구할 수 없습니다.',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_Finish_1                 :  '경매와 관련되지 않았습니다.',
'경매와 관련이 없습니다.',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_Finish_2                 :  '이 주소는 경매의 낙찰자도 경매 판매자도 아닙니다.',
'이 주소는 경매 낙찰자나 판매자가 아닙니다.',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_Finish_5                 :  'TX 해시를 클릭하면 도메인을 DomainSale에 전송한 결과가 성공했는지 확인할 수 있습니다.',
'당신의 TX 해시를 클릭하면 도메인을 DomainSale에게 성공적으로 전송했는지 확인할 수 있습니다.',

2018-05-31 15:41 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_1                  :  '잘못된 지갑',
'판매를 위한 매도호가',

2018-05-31 15:45 UTC, miner7222 requested changes

2018-05-31 15:45 UTC, jjhitel commented on app/scripts/translations/ko.js
> +GAS_Price_3                     : '고속',
'매우 빠름'

2018-05-31 15:45 UTC, jjhitel commented on app/scripts/translations/ko.js
> +SWAP_Warning_1                  :  '경고! 교환을 완료하기위한 충분한 자금이 없습니다.',
'경고! 교환을 완료하기 위한 충분한 자금이 없습니다.'

2018-05-31 15:45 UTC, jjhitel commented on app/scripts/translations/ko.js
> +X_HelpfulLinks_4                :  'MyEtherWallet으로부터 지갑 이전',
'MyEtherWallet으로/으로부터 지갑 이전'

2018-05-31 15:45 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__1      :  '당신의 안전을 위해서 다음 사항을 이해해주시기 바랍니다. 🙏',
'당신의 안전을 위하여 다음 사항을 숙지해주시기 바랍니다. 🙏'

2018-05-31 15:45 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_content__1     :  '피싱사이트는 MyEtherWallet, EtherDelta, Paypal또는 은행과 똑같이 보이는 웹 사이트에 대한 링크가 포함된 메시지를 보내지만 실제진짜 웹 사이트는 아닙니다. 그들은 당신의 정보를 훔치고 당신의 돈을 훔칩니다.',
'피싱 사이트는 MyEtherWallet, EtherDelta, Paypal 또는 은행과 유사한 웹 사이트 링크가 담긴 메시지를 보내지만, 진짜 웹 사이트가 아닙니다. 그들은 당신의 정보와 돈을 훔칩니다.'

2018-05-31 15:51 UTC, miner7222 requested changes

2018-05-31 15:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ADD_Radio_5_PathCustom      : '사용자정의 ',
'사용자 정의'

2018-05-31 15:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +TOKEN_Addr                  : '토큰 Contract 주소 ',
'토큰 컨트랙트 주소 '

2018-05-31 23:17 UTC, dakeshi reviewed
DOMAIN_offer_1,2,3번 영문이 없습니다. 확인바랍니다.

2018-05-31 23:17 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_5                  :  '도메인을 판매하려면 아래 두 가격 중 하나를 설정하세요. 잠가 둔 모든 자금은 구매자에게 돌아가고 판매되는 자금의 10%는 참조자에게 돌아간다는 것을 기억하세요.',
'당신의 도메인을 판매하기 위해 매도호가를 제시하려면 아래 두 가격 중 하나를 설정하세요. 도메인 증서 안에 묶인 자금은 매수자에게 이전되며, 도메인이 팔릴 때 해당 기금의 10%가 참조자에게 주어집니다.',

2018-05-31 23:17 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_1                  :  '잘못된 지갑',
DOMAIN_offer_1, 2, 3번에 해당하는 영문이 보이질 않네요. en 버전에는 존재합니다. 확인바랍니다.

2018-05-31 23:17 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_2                  :  '잠금 해제한 지갑이 지갑이 해당 이름을 소유하고 있지 않습니다.',
'잠금 해제한 지갑이 이 이름을 소유하고 있지 않습니다.',

2018-06-01 01:09 UTC, dakeshi reviewed
2차 리뷰 마무리합니다. 경매와 관련해서는 bid/offer를 입찰가/판매가로 번역했으며 경매 winner는 낙찰자로 적용했습니다. 추가로 contract 번역과 관련해서는 외래어 표기 용어집에는 `콘트랙트`로 표기되어 있음을 확인했습니다. contract 농업에 관련된 내용이었지만요. (https://www.korean.go.kr/)

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_7                  :  '제안 변경:',
'판매가 변경:',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_8                  :  '도메인 판매 제안을 변경하려면 아래 두 가격 중 하나를 변경하십시오. 당신이 도메인의 행위에 대해 잠가 둔 모든 자금은 구매자에게 돌아가고 판매되는 자금의 10%는 참조자에게 돌아간다는 것을 기억하세요.',
'도메인 판매가를 변경하려면 아래 두 가격 중 하나를 변경하세요. 도메인 증서 안에 묶인 자금은 매수자에게 이전되며, 도메인이 팔릴 때 해당 기금의 10%가 참조자에게 주어집니다.',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_10                 :  '이는 누군가가 도메인을 즉시 살 수 있는 가격입니다. 0은 도메인을 즉시 구입할 수 없음을 의미합니다.',
'도메인을 즉시 매수할 수 있는 가격을 나타냅니다. 0은 도메인을 즉시 매수할 수 없다는 것을 의미합니다.',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_11                 :  '이는 누군가가 도메인 경매를 시작할 수 있는 가격입니다. 0은 도메인 경매를 할 수 없음을 의미합니다.',
'도메인 경매를 시작할 수 있는 가격을 나타냅니다. 0은 도메인을 경매할 수 없다는 것을 의미합니다.',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_12                 :  '도메인 제공',
'도메인 판매하기',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +DOMAIN_offer_15                 :  '도메인 판매를 취소할 수 있습니다. 도메인은 되돌려지고 뮤료입니다. 도메인에 대한 입찰이 접수되기 전까지만 사용가능합니다.',
'도메인 판매를 취소할 수 있습니다. 도메인은 당신에게 다시 돌아가며 이때 비용은 발생하지 않습니다. 도메인 판매 취소는 도메인에 대한 입찰가가 접수 되기 전에만 가능합니다.',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_WrongAddress_1              :  '잠금이 해제된 지갑에 이름이 없습니다 ',
'잠금 해제한 지갑이 이 이름을 소유하고 있지 않습니다.',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Finalize_content            :  'ESN 이름을 낙찰자에게 할당하고 종료합니다. 당첨자는 입찰 가격과 그 다음으로 가장 높은 입찰가의 차이를 환불 받게 됩니다. 만약 당신이 유일한 입찰자라면, 0.01 ETH를 제외한 모든 금액을 환불 받을 것입니다. 낙찰받지 못한 모든 사람도 환불받습니다.',
'ENS 이름을 낙찰자에게 양도하고 경매를 종료합니다. 낙찰자는 자신의 매수호가와 다음으로 가장 높은 매수호가 차액을 환불받을 수 있습니다. 만약 당신이 유일한 입찰자라면, 0.01 ETH를 제외한 모든 금액을 환불받을 것입니다. 낙찰받지 못한 모든 사람도 환불받을 수 있습니다.',

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_1                    :  '경매의 과정은?',
'경매 과정은 다음과 같습니다.',

문자열 확인할 수 있는 url: https://www.myetherwallet.com/#ens

2018-06-01 01:09 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_3                    :  '어떤 계정으로 이름을 소유하려 하는지 그리고 계정에 여러개의 백업이 있는지 확인합니다..',
'어떤 계정으로 이름을 소유할지 결정하고, 해당 계정에 대한 백업을 여러 개 가지고 있는지 확인합니다.',

2018-06-01 02:39 UTC, dakeshi reviewed
onboard 앞부분까지 리뷰 마쳤습니다.

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_4                    :  '이름에 대해 지불할 ETH 최대 액을 결정합니다(<u>입찰 금액</u>). 입찰가 + 가스 가격으로 0.01 ETH를 충분히 가진 계정인지 확인하세요.',
'이름 구매를 위해 사용할 ETH 수량을 결정합니다(<u>입찰 금액</u>). 입찰가 + 가스(0.01 ETH)를 충분히 처리할 수 있는 계정인지 확인하세요.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_7                    :  '<u>이름</u> 및 <u>입찰단가</u>, <u>입찰 마스크>를 입력해야 하며, 이는 <u>비밀 번호</u>로 보호됩니다.',
'<u>이름</u>, <u>입찰단가</u>, <u>비밀 번호</u>로 보호되는 <u>입찰 마스크</u>를 입력합니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_8                    :  '입찰가는 당신이 공개하기 전까지 비밀로 유지됩니다.',
'이로 인해 입찰 주문이 접수되지만,  이 정보는 당신이 공개하기 전까지 비밀로 유지됩니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_9                    :  '3) 입찰 공개',
'3) 입찰가 공개',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_13                   :  '두 당사자가 정확히 같은 금액을 입찰할 경우, 첫번째 입찰이 낙찰됩니다.',
'두 명이 같은 금액으로 입찰한 경우, 입찰가를 먼저 공개한 사람에게 낙찰됩니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_15                   :  '경매가 종료되면 (5일 후/ 120시간), 당첨자는 새 이름을 청구하기위해 경매를 종료해야 합니다.',
'경매가 종료되면 (5일 후/ 120시간), 낙찰자는 새 이름을 청구하기위해 경매를 종료해야 합니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_16                   :  '당첨자는 입찰 가격과 그 다음으로 가장 높은 입찰가의 차이를 환불 받게 됩니다. 당신이 유일한 입찰자라면, 당신은 0.01 ETH를 제외한 모든 자금을 환불 받습니다.',
'낙찰자는 자신의 입찰가와 다음으로 가장 높은 입찰가 사이의 차액을 환불받을 수 있습니다. 입찰자가 한 명이라면, 0.01 ETH를 제외한 모든 금액을 환불받을 것입니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_17                   :  '정보 더보기',
'추가 정보',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_18                   :  '등기소를 위한 경매는 설명되어있듯이 블라인드 경매이며',
'이 registrar를 위한 경매는 블라인드 경매이며, 이곳에 서술되어 있습니다',

> registar는 적절한 번역어가 없어서 원문을 유지했습니다. 설명은 이곳에 나와있네요.
https://docs.ens.domains/en/latest/introduction.html?highlight=registrar
Top-level domains, like ‘.eth’ and ‘.test’ are owned by smart contracts called registrars, which specify rules governing the allocation of their subdomains.

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_19                   :  '기본적으로, 경매기간동안 누구도 "어떤 것도* 볼 수 없습니다.',
'기본적으로, 모든 사람은 경매 기간 동안 *어떤 것도* 볼 수 없습니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_20                   :  'ENS: 설명서 읽기',
'ENS: 문서 보기',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_21                   :  'Ethereum Name Service(ENS) 재시작 날짜 발표!',
'Ethereum Name Service(ENS) 재출시일 공지!'

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_22                   :  '지식 베이스: ENS',
'도움말 센터: ENS',

> knowledge base는 도움말 센터에 가까운 형태라 도움말 센터로 번역했습니다.

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_23                   :  '디버그 [BAD INSTRUCTION] 추적',
'입찰가 공개 디버깅하기',

> bad instruction은 입찰가 공개를 할 때 잘못된 절차를 밟아서 정상적으로 입찰가 공개가 이루어지지 않은 경우를 말하는 것 같습니다. bad instruction은 일단 번역하지 않고 놔뒀습니다. 참고문서 https://myetherwallet.github.io/knowledge-base/ens/ens-debugging-a-bad-instruction-reveal.html
가

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Helper_24                   :  '현재 발견된 이슈에 대한 지원요청 티켓의 심각한 지연이 발생하고 있습니다. 죄송합니다. :(',
'입찰가 공개 관련 이슈에 대한 지원 처리가 지연되고 있습니다. 지원 요청을 하기 전에 위의 문서를 참고해서 문제 해결을 시도해보시길 바랍니다.',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Reveal_Title                :  '입찰가 공개',
'입찰가 공개하기',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ENS_Start_Title                 :  '경매 시작',
'경매 시작하기',

2018-06-01 02:39 UTC, dakeshi commented on app/scripts/translations/ko.js
> +EOS_01                          :  '**EOS 키-쌍 생성**',
EOS는 메인넷 출시를 앞두고 있기 때문에 지금 시점에서 번역하는 것이 의미가 있을지 의문이네요. 확인부탁드립니다.

2018-06-01 03:39 UTC, hackmod commented
@dakeshi 님 수고 많으셨습니다~
아주 일부만 빼고 거의 다 반영했습니다~

> You are currently winning this auction with the highest bid. You can bid higher if you want, but it will delay the close of the auction for 24 hours.
> 최고 입찰가로 현재 경매의 낙찰가능성이 높습니다. 더 높은 가격으로 입찰할 수 있으나 경매 마감 시간이 24시간 지연될 수 있습니다.

일단 커밋하고 저녁에 정리하여 rebase하도록 하겠습니다~

2018-06-01 06:05 UTC, dakeshi reviewed
onboard 섹션까지 리뷰 완료

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__2      :  '이를 조심하지 않으면 당신의 자산은 도난당할 수 있습니다.',
'이 경고들을 무시하면 당신의 자금은 도난당할 수 있습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__3      :  '이 창이 불편한 점이 있을 것입니다. 이점은 죄송합니다.',
'클릭해서 넘어가는 것이 짜증나는 일이라는 것을 저희도 잘 알고 있습니다. 죄송합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__5      :  'MyEtherWallet은 자유롭게 쓸 수 있는 무료의 오픈소스 클라이언트 인터페이스 입니다.',
'MyEtherWallet은 무료 오픈소스 클라이언트 인터페이스입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__6      :  '이 사이트는 당신의 키와 자금에 대한 전적인 컨트롤을 유지하면서 블록체인과 상호작용을 할 수 있게끔 지원합니다.',
'키와 자금은 당신이 완전히 통제하며, 블록체인과 직접 상호작용할 수 있습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__7      :  '**당신만이** **유일하게** 보안에 책임이 있습니다.',
'보안은 모두 **당신** 책임입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__8      :  '피싱 사이트 혹은 개인 키를 잊었을 경우에 당신의 자금을 복구하거나 계정 동결을 지원 하지 못합니다.',
'피싱 사이트를 방문하거나 개인 키를 분실한 경우, 저희는 당신의 자금을 복구하거나 계정을 동결할 수 없습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_bank_content__1         :  '은행이나 거래소에서 계정을 열게되는 경우, 은행은 그들의 시스템에 계정을 만듧니다.',
'은행이나 거래소에서 계정을 만들면, 그들의 시스템에 당신의 계정을 생성합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_bank_content__2         :  '은행은 개인 정보, 비번, 잔고 및 트랜잭션과 당신의 돈을 보존합니다.',
'은행은 당신의 개인 정보, 비밀 번호, 잔액, 트랜잭션, 그리고 돈을 계속 파악합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_bank_content__3         :  '은행은 계정과 여러 서비스 제공에 대한 댓가 지불을 요구하는데 예를 들어 카드를 분실당했을 경우에 환급 거래같은 서비스를 제공합니다.',
'은행은 계좌 관리와 서비스 제공을 위해 수수료를 부과합니다. 예시: 카드 분실 시 환불 트랜잭션 서비스.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_bank_content__4         :  '은행은 당신이 돈을 송금하기 위해 수표를 쓰거나, 온라인으로 잔액을 확인하고, 비밀 번호를 재설정하고, 만약 당신이 그것을 분실하면 새로운 직불 카드를 발급해 줍니다.',
'은행은 송금을 위한 직불 카드 결제나 수표 발행, 온라인 잔액 확인, 비밀 번호 초기화, 직불 카드 분실시 새로운 카드 발급 등의 서비스를 제공합니다.'

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_bank_content__5         :  '*은행이나 거래소 계좌*가 있을때 그들은 당신이 얼마나 많은 돈을 보낼 수 있는지, 어디로 보낼 수 있는지, 그리고 의심스러운 예금을 얼마나 오래 보유할지 결정합니다. 모두 수수료를 물리고.',
'*은행이나 거래소에 계좌*를 가지고 있으면, 그들은 돈을 얼마나 보낼 수 있는지, 어디로 보낼 수 있는지, 의심스러운 예금을 얼마나 오래 보유할 수 있는지 등을 결정합니다. 이러한 모든 활동에는 수수료가 부과됩니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__1    :  'MyEtherWallet에서 계정을 생성할 경우, 개인 키 및 퍼블릭 키(주소)와 같은 암호화 숫자 세트를 생성합니다.',
'MyEtherWallet에서 계정을 만들면, 개인 키와 공개 키 (주소)로 구성된  암호화 숫자 세트가 생성됩니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__2    :  '키 처리는 전적으로 컴퓨터 브러우저 내부에서 처리됩니다.',
'키 처리는 전적으로 컴퓨터 브라우저 내부에서 처리됩니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__3    :  '여러분의 개인 키, 암호 또는 기타 계정 정보를 전송, 수신 또는 저장하지 않습니다.',
'저희는 절대로 당신의 개인 키, 비밀 번호, 또는 기타 계정 정보를 저장하거나 전송, 수신하지 않습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__4    :  '거래 수수료는 청구하지 않습니다.',
'저희는 트랜잭션 수수료를 부과하지 않습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__5    :  '단순히 **인터페이스**를 사용하여 블록 체인과 **직접 상호 작용**하게 됩니다.',
'당신은 **블록체인과 직접** 상호 작용하기 위해 간단히 우리의 **인터페이스**를 사용합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__6    :  '*공개 키(주소)*를 다른 사용자에게 보내면, 해당 사용자는 ETH혹은 토큰을 보낼 수 있습니다. 👍',
'*공개 키(주소)*를 다른 사용자에게 보내면, 그들은 ETH 또는 토큰을 당신에게 보낼 수 있습니다. 👍',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__7    :  '만역 *개인 키*를 다른 사용자에게 보내면, 그는 계정의 모든 권한을 가지게 됩니다. 👎',
'*개인 키*를 다른 사용자에게 보내면, 그들은 당신 계정에 대한 모든 권한을 갖게 됩니다. 👎',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_title__alt   :  '블록체인은 무엇인가?',
'블록체인이란?',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__1   :  '블록체인은 거대한, 전세계적인, 분산된 스프레드시트와 같습니다.',
'블록체인은 거대한, 전세계적인, 분권형 스프레드시트와 같습니다.',

> decentralized는 분권형으로 번역했습니다. 분산된은 distributed에 해당합니다.

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__2   :  '이는 누가 얼마나 많은 코인을 보냈는지, 각 계좌의 잔고는 얼마인지를 보관합니다.',
'블록체인은 누가 누구에게 코인을 얼마나 보냈는지, 각 계정의 잔고는 얼마인지 계속 파악합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__3   :  '이는 특정한 컴퓨터를 가진 전세계 수천명의 사람들에 의해 보존되고 유지됩니다.',
'특별한 컴퓨터를 가진 전 세계 수많은 사람(채굴자)이 블록체인을 저장하고 관리합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__4   :  '블록체인의 블록은 다양한 지갑, MyEtherWallet, MetaMask, Exodus, Mist, Geth, Parity 및 그밖의 것을 통해 전송된 개별 트랜잭션으로 구성됩니다.',
'블록체인의 블록은 MyEtherWallet, MetaMask, Exodus, Mist, Geth, Parity 등에서 전송된 및 모든 개별 트랜잭션으로 구성되어 있습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__5   :  'MyEtherWallet.com 혹은 [etherscan.io](https://etherscan.io)을 통해서 보는 잔고는 블록체인의 데이터를 보고있는 것이며, 개인 시스템의 것을 보는 것이 아닙니다.',
'MyEtherWallet.com에서 잔액을 확인하거나 [etherscan.io](https://etherscan.io)에서 트랜잭션을 볼 때, 당신은 우리 개인 시스템에 있는 데이터가 아니라 블록체인의 데이터를 보고 있는 것입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__6   :  '재차: **우리는 은행이 아닙니다**.',
'다시 한번 말하지만: **우리는 은행이 아닙니다**.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_title__alt          :  '그런데...이게 대체 뭔상관?',
'하지만..이게 왜 중요하죠?',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__1          :  '왜냐하면 당신은 다음과 같은 것을 알아야 합니다. 즉, 우리는 **못합니다**...',
'왜냐하면 당신은 우리가 **할 수 없는** 것을 알고 있어야하기 때문입니다',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__2          :  '계좌에 접근하고 송금을 대신하는 일.',
'당신의 계좌에 접근하거나 송금을 대신하는 일.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__3          :  '개인 키를 복구하거나 변경하는 일.',
'당신의 개인 키를 복구하거나 변경하는 일.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__4          :  '비밀번호를 복구나 리셋을 하는 일.',
'당신의 비밀번호를 복구하거나 재설정하는 일.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__5          :  '거래 되돌리기, 취소 혹은 트랜잭션 재입금.',
'트랜잭션 되돌리기, 취소 또는 환불.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__7          :  '**당신** 그리고 **당신만이** 이 모든 보안 책임을 지게됩니다.',
'보안은 모두 **당신** 책임입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__8          :  '개인 키와 암호를 안전하게 유지하기 위해 부지런해야 합니다. 개인 키는 때때로 mnemonic 문구, keystore 파일, UTC파일, JSON파일, 지갑 파일이라고도 합니다.',
'개인 키와 비밀번호를 안전하게 유지하려면 부지런해야 합니다. 개인 키는 때때로 mnemonic 문구, keystore 파일, UTC 파일, JSON파일, 지갑 파일을 의미하기도 합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__9          :  '개인 키 또는 암호를 분실한 경우 아무도 복구할 수 없습니다.',
'개인 키나 비밀번호를 잃어버리면, 아무도 그것을 복구할 수 없습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_why_content__10         :  '피싱 웹 사이트에서 개인키를 입력할 경우에, **모든 자금이 탈취됩니다**.',
'피싱 웹 사이트에서 개인키를 입력할 경우에, **모든 자금을 잃게될 것입니다**.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_title            :  'MyEtherWallet이 할수 없는것이라면 요점은 무언가?',
'MyEtherWallet이 이러한 것들을 할 수 없다면 요점이 무엇인가?',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_point_title__alt        :  'Mew는 또 무엇인가?',
'Mew이 말하고 싶은 것이 무엇인가?',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_content__1       :  '그것이 블록체인과 분산화의 관점입니다.',
'그것이 블록체인과 분권화의 요점이기 때문입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_content__2       :  '자금을 옮기고 싶을 때에 은행, 정부 혹은 혹은 누군가에게 의존할 필요가 없습니다.',
'자금을 옮기고 싶을 때, 은행, 정부 또는 누군가에게 의존할 필요가 없습니다.'

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_content__3       :  '자금을 안전하게 지키기 위해 거래도나 은행의 보안에 의존할 필요가 없다.',
'자금을 안전하게 지키기 위해 거래소나 은행의 보안에 의존할 필요가 없습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_content__4       :  '만약 이러한 것들이 가치 있다고 생각하지 않는다면, 왜 블록 체인과 암호 체계가 가치 있다고 생각하는지 스스로 물어 보세요. 😉',
'이러한 것들에서 가치를 발견하지 못한다면,  왜 블록 체인과 암호 화폐가 가치있다고 생각하는지 스스로 물어 보세요. 😉',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_content__5       :  '이런 얘기가 마음에 들지 않는다면 [Coinbase](https://www.coinbase.com/) 또는 [Blockchain.info](https://blockchain.info/wallet/#/signup)를 사용하세요. 디들은 사용자 이름과 비밀 번호에 익숙한 계정을 지원합니다.',
'이런 이야기가 마음에 들지 않는다면 [Coinbase](https://www.coinbase.com/) 나 [Blockchain.info](https://blockchain.info/wallet/#/signup)를 사용하세요. 그들은 사용자 이름과 비밀 번호로 구성된 더 익숙한 계정 형태를 지원합니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_whymew_content__6       :  '걱정스러워도 MEW를 사용하고자 한다면, [하드웨어 지갑을 구하세요](https://myetherwallet.github.io/knowledge-base/hardware-wallets/hardware-wallet-recommendations.html)! 키를 안전하게 보존해줍니다.',
'MEW를 사용하고 싶지만 걱정된다면, [하드웨어 지갑을 구하세요](https://myetherwallet.github.io/knowledge-base/hardware-wallets/hardware-wallet-recommendations.html)! 안전하게 키를 보존해줄 것입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_title            :  '어떻게 하면 당신과 당신 자금을 지킬 수 있을까',
'당신과 당신 자금을 지키는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_title          :  '피싱사이트로부터 안전할 수 있을까',
'피싱범으로부터 자신을 지키는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_content__2     :  '[EAL](https://chrome.google.com/webstore/detail/etheraddresslookup/pdknmigbbbhmllnmgdfalmedcmcefdfn)을 설치하거나 [MetaMask](https://chrome.google.com/webstore/detail/me
'[EAL](https://chrome.google.com/webstore/detail/etheraddresslookup/pdknmigbbbhmllnmgdfalmedcmcefdfn)을 설치하거나 [MetaMask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn) 또는 [Metacert 에서 제공하는 Cryptonite](https://chrome.google.com/webstore/detail/cryptonite-by-metacert/keghdcpemohlojlglbiegihkljkgnige) 또는 [MyEtherWallet 크롬 확장 프로그램](https://chrome.google.com/webstore/detail/myetherwallet-cx/nlbmnnijcnlegkjjpcfjclmcfggfefdm)을 설치해서 악의적인 웹사이트를 차단하세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_content__5     :  '여기저기서 오는 이메일, Slack, Reddit, 트위터, 기타 등등의 정체불명의 메시지나 링크를 믿지마세요.',
'이메일, Slack, Reddit, 트위터 등에서 오는 무작위로 발송된 메시지나 링크를 믿지마세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_content__6     :  '정보를 입력하기 전에 항상 사이트로 직접 이동하세요. 메시지 또는 전자 메일에서 링크를 클릭한 후 정보를 입력하지 마세요.',
'정보를 입력하기 전에 항상 사이트로 직접 이동하세요. 메시지 또는 이메일에서 온 링크를 클릭해서 정보를 입력하지 마세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_title          :  '스캠으로부터 안전해지려면',
'스캠으로부터 자신을 보호하는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_content__1     :  '그들은 아무 유익 없이 돈을 요구할 것입니다.',
'아무 것도 돌려주지 않는데도 돈을 달라고 요구할 것입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_content__2     :  '믿기지 않게 좋다면, 바로 스캠입니다.',
'믿기지 않을 정도로 정말 좋다면, 그것은 아마도 스캠입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_content__3     :  '어떤 프로젝트에 돈을 보내기 전에 확인을 하세요. 다양한 웹 사이트와 포럼에서 이에 대한 정보를 찾아봅니다. 주의하세요.',
'누군가나 어떤 프로젝트에 돈을 보내기 전에 확인을 하세요. 다양한 웹 사이트와 포럼에서 이에 대한 정보를 찾아보세요. 주의하세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_content__4     :  '질문을 하세요. 이해하기 어렵거나 맞지 않는다고 생각한다면.',
'이해가 안되거나 옳지 않다고 생각되는 점이 있으면 질문하세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_title          :  '손실로부터 자신을 보호하기',
'개인 키나 비밀번호를 분실하지 않는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_content__1     :  '개인키 혹은 비번을 잊는다면, 영원히 끝입니다. 잃지 마세요.',
'개인 키 또는 비밀번호를 잃어버리면 영원히 끝입니다. 분실하지 마세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_content__2     :  '개인 키와 암호를 백업합니다. 컴퓨터에만 저장하지 마세요. 종이에 인쇄하거나 USB드라이브에 저장합니다.',
'개인 키와 비밀번호를 백업하세요. 컴퓨터에만 저장하지 마세요. 종이에 인쇄하거나 USB드라이브에 저장하세요.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_content__3     :  '용지 또는 USB드라이브를 다른 곳에 저장합니다. 노트북과 함께 화재나 홍수로 인해 백업이 파괴된 경우에는 백업이 유용하지 않습니다.',
'이 종이나 USB 드라이브를 물리적으로 다른 장소에 저장하세요. 화재나 홍수로 인해 노트북이 고장나면 백업은 무용지물입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_content__4     :  'Dropbox, GoogleDrive또는 기타 클라우드 저장소에 개인 키를 저장하지 마세요. 만약 계좌가 손상되면, 자금은 도난당할 것입니다.',
'Dropbox, Google Drive 또는 기타 클라우드 저장소에 개인 키를 저장하지 마세요. 계정이 손상되면, 자금은 도난당할 것입니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_content__5     :  '1주 보수정도 되는 가치의 가상화폐를 가지고 있다면, 하드웨어 지갑을 구입하세요. 그만한 가치가 있어요.',
'암호 화폐의 가치가 1주일치 보수보다 높다면, 하드웨어 지갑을 구입하세요. 그만한 가치가 있습니다.',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__1        :  '지갑 생성',
'지갑 만들기',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__2        :  '하드웨어 지갑 구하기',
'하드웨어 지갑 구매하기',

> 하드웨어 지갑 추천 링크로 연결되네요.

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__3        :  'MEW + MetaMask 사용하기',
'MEW + MetaMask 설정 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__4        :  'MEW 오프라인 / 로컬 사용하기',
'오프라인 / 로컬에서 MEW을 사용하는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__5        :  'Ledger 하드웨어 지갑으로 보내기',
'Ledger 하드웨어 지갑에서 전송하는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__6        :  'TREZOR 하드웨어 지갑으로 보내기',
'TREZOR 하드웨어 지갑에서 전송하는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__7        :  'MetaMask로 보내기',
'MetaMask에서 전송하는 방법',

2018-06-01 06:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__8        :  '더 배우기 혹은 이곳에 연락하기',
'더 배우기 또는 우리에게 연락하기',

2018-06-01 08:36 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__7      :  '**당신만이** **유일하게** 보안에 책임이 있습니다.',
강조하는 문장이 제대로 표현 안되고 있으나, 가장 자연스럽긴 하네요

2018-06-01 09:03 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__4    :  '거래 수수료는 청구하지 않습니다.',
은행에 대비해서 "거래" 수수료라고 하는게 맞지 않을까요? 이더리움 트랜잭션은 gas fee로 물리고 있으니?

2018-06-01 09:06 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__1   :  '블록체인은 거대한, 전세계적인, 분산된 스프레드시트와 같습니다.',
구글번역 넣어도 분권형이라고 나왔지만 좀 생소하지 않나요? "분권형 블록체인" 검색하면 10개도 안나오네요.

2018-06-01 09:13 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__5   :  'MyEtherWallet.com 혹은 [etherscan.io](https://etherscan.io)을 통해서 보는 잔고는 블록체인의 데이터를 보고있는 것이며, 개인 시스템의 것을 보는 것이 아닙니다.',
MyEtherWallet.com 혹은 [etherscan.io](https://etherscan.io)을 통해서 보는 잔고는 개인 시스템의 것을 보는 것이 아닌 블록체인의 데이터를 보고 있는 것입니다.

2018-06-01 09:44 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__8        :  '더 배우기 혹은 이곳에 연락하기',
수고하셨습니다~ 👍

2018-06-01 10:17 UTC, miner7222 requested changes

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +GEN_Help_MetaMask               :  '간단합니다! 키는 피싱사이트가 아닌 MetaMask에 보존됩니다. 지금 연결해보세요.',
'간단합니다! 키는 피싱 사이트가 아닌 MetaMask에 보관됩니다. 지금 연결해보세요.'

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +HELP_7_Desc_7               : '사용자정의’ 버튼을 클릭합니다. ',
'사용자 정의’ 버튼을 클릭합니다. '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_title           :  'MyEtherWallet.com에 오신것을 환영합니다.',
'MyEtherWallet.com에 오신 것을 환영합니다.'

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +SEND_custom                 : '사용자정의 토큰 추가 ',
'사용자 정의 토큰 추가 '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +NODE_Title                  : '사용자정의 노드 설정하기 ',
'사용자 정의 노드 설정하기 '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +NODE_CTA                    : '사용자정의 노드 저장 또는 사용 ',
'사용자 정의 노드 저장 또는 사용 '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +HELP_7_Title                : '7) 어떻게 토큰 전송하기 및 사용자정의 토큰을 추가할 수 있나요? ',
'7) 어떻게 토큰을 전송하고 사용자 정의 토큰을 추가할 수 있나요? '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
>  HELP_8_Desc_2               : '만약 MyEtherWallet.com 이 다운된다면, 다른 대안 도구 (geth 또는 Ethereum Wallet / Mist 등)을 사용해야 합니다. MyEtherWallet 에서 이더리움을 꺼내야 할 필요는 없습니다. 이더리움들은 MyEtherWallet.com 을 통해서 생성된 지갑 내에 존재합
'만약 MyEtherWallet.com이 다운된다면, 다른 대안 도구 (geth 또는 Ethereum Wallet / Mist 등)를 사용해야 합니다. MyEtherWallet에서 이더리움을 꺼내야 할 필요는 없습니다. 이더리움은 MyEtherWallet.com을 통해서 생성된 지갑 내에 존재합니다. '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
>  HELP_SecCX_Desc_6           : '닉네임과 지갑 주소를 암호화하면 계좌 잔액과 닉네임들을 확인할 때마다 비밀번호를 입력해야 합니다. 보안이 걱정된다면 Chrome 확장 프로그램 대신 MyEtherWallet.com 을 사용해주세요. ',
'닉네임과 지갑 주소를 암호화하면 계좌 잔액과 닉네임을 확인할 때마다 비밀번호를 입력해야 합니다. 보안이 걱정된다면 Chrome 확장 프로그램 대신 MyEtherWallet.com을 이용해주세요. '

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_content__2     :  '[EAL](https://chrome.google.com/webstore/detail/etheraddresslookup/pdknmigbbbhmllnmgdfalmedcmcefdfn)을 설치하거나 [MetaMask](https://chrome.google.com/webstore/detail/me
[MyEtherWallet Chrome 확장 프로그램]

2018-06-01 10:17 UTC, jjhitel commented on app/scripts/translations/ko.js
> +NONCE_Desc                  : 'nonce는 주어진 주소에소 보낼 TX의 회수입니다. 이는 트랜잭션이 순차적으로 이루어지고 한번 이상 이루어지지 않도록 보장해줍니다.',
'nonce는 주어진 주소에서 보낸 TX의 개수입니다. 이는 트랜잭션이 순차적으로 이루어지고 여러 번 이루어지지 않도록 보장해줍니다.'

2018-06-01 14:05 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__7      :  '**당신만이** **유일하게** 보안에 책임이 있습니다.',
only까지 강조를 넣은 후보군으로 '보안에 대한 책임은 **전적으로 당신**에게 있습니다.' 정도가 있을 것 같네요. 최대한 원문을 살려보려 했는데 자연스럽지 않아서 간략하게 번역했습니다.

2018-06-01 14:15 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_interface_content__4    :  '거래 수수료는 청구하지 않습니다.',
`거래`의 사전적 의미는 `주고 받는 것`이며 영어에서는 `trade`가 이에 해당합니다.[금융 용어 사전](https://www.fsc.go.kr/know/wrd_list.jsp?menu=7420000&bbsid=BBS0026)에서는 transaction에 대해 `거래`라는 번역을 사용한 예문도 있지만 아래의 정의들을 기준으로 본다면 `트랜잭션`과 `거래`는 별개로 취급해야 한다는게 제 생각입니다.

http://www.zdnet.co.kr/news/news_view.asp?artice_id=20180527085440&type=det&re=
> 트랜잭션은 하나의 외부 거래를 기록하기 위해 컴퓨터 시스템 내부에서 완료돼야 하는 일련의 처리 동작을 뜻한다.

https://coin.theinfo.kr/transaction/
> 단어 뜻은 거래를 뜻하고 금융에서의 쉬운 예는 ATM 기기에서 인출할 때 정보를 입력-조회-인출의 일련의 과정이 하나의 트랜잭션이다. 입력한 정보가 불일치하면 아무일도 없는 상태로 되돌리는 것 까지 포함해서.

이를 토대로 판단해 볼 때 트랜잭션을 거래로

2018-06-01 14:26 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__1   :  '블록체인은 거대한, 전세계적인, 분산된 스프레드시트와 같습니다.',
우선, 분권과 분산은 명백히 다른 뜻입니다. 이들 용어에 대한 https://dictionary.cambridge.org/ 에서의 의미입니다.

decentralize
> to move the control of an organization or government from a single place to several smaller ones:

distribute
> to give something out to several people, or to spread or supply something:

decentralized를 번역에 대해서 좀 더 이야기 하자면, 제 번역 원칙은 우선 순위는 다음과 같습니다.
1. 사전적 의미
2. 사전에 정의된 용어가 여러 개일 경우 가장 명확하게 의미를 전달할 수 있는 단어
3. 사전에는 나와있지 않거나 뒷부분에 언급되지만 사람들 사이에서 자주 사용되는 단어
4. 1-3에 해당하지 않는 경우 영어를 한글 발음으로 표기.

decentralized를 `분권형`으로 번역한 이유는 1, 2번 기준에 따른 결정입니다.
de는 opposite의 의미가 담겨있으니 중앙집권형의 반대는 분권형입니다.
요즘 decentralized에 대해 `탈중앙화`라는 번역을 사용하고 있는데(제 원칙에 따르면 3번 기준에 해당합니다.)
저는 이와 같은 번역에 대해서는 반대하는 입장입니다. 
decentralized에서 가장 전달하고 싶은 의미는 권력의 분산이기 때문에 `분권형`이 가장 적합한 번역이라고 생각합니다.

2018-06-01 14:37 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__5   :  'MyEtherWallet.com 혹은 [etherscan.io](https://etherscan.io)을 통해서 보는 잔고는 블록체인의 데이터를 보고있는 것이며, 개인 시스템의 것을 보는 것이 아닙니다.',
우선, `잔고` 대신 `잔액`을 사용한 이유는 맞춤법 검사 결과의 제안을 받아들였기 때문입니다.

우리말 맞춤법 검사기 중 가장 신뢰성 높은 맞춤법 검사기인 [부산대 맞춤법 검사기](http://speller.cs.pusan.ac.kr/PnuWebSpeller/lib/check.asp)에서 `잔고`에 대해 검사한 결과는 다음과 같습니다.

> 접미사 '-고(高)'는 일본어에서 온 말입니다. 우리말에 적합한 접두사 형태로 바꿔 쓰십시오.  
(예) 보유고 (x) -> 보유액 (o)      생산고 (x) -> 생산량 (o)

 영어 원문에서는 etherscan.io 에서는 트랜잭션을 확인한다고 설명되어 있기 때문에 잔액을 확인하는 것과는 다른 동작이라 MEW와 ehterscan.io 모두 잔액을 확인한다는 번역이 맞지 않다고 생각합니다.

2018-06-01 15:38 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__5   :  'MyEtherWallet.com 혹은 [etherscan.io](https://etherscan.io)을 통해서 보는 잔고는 블록체인의 데이터를 보고있는 것이며, 개인 시스템의 것을 보는 것이 아닙니다.',
헉... 잔고 잔액이 다른 뜻인 줄 알았는데.. @@

2018-06-01 16:38 UTC, hackmod commented on app/scripts/translations/ko.js
> +EOS_01                          :  '**EOS 키-쌍 생성**',
일단 번역한 채로 두었습니다

2018-06-01 18:08 UTC, miner7222 requested changes

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__6      :  '이 사이트에서는 당신의 키와 자금에 대한 통제하에 블록체인과 직접적인 상호작용을 할 수 있도록 지원합니다.',
통제 하에

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +ENS_Helper_15                   :  '경매가 종료되면 (5일 후/ 120시간), 낙찰자는 새 이름을 청구하기위해 경매를 종료해야 합니다.',
청구하기 위해

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +ENS_Helper_19                   :  '기본적으로, 모든 사람은 경매기간동안 *어떤 것도* 볼 수 없습니다.',
경매기간 동안

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +tx_notFound_4               : '오른쪽 상단에 있는 드롭 다운 목록을 사용하여 다른 ETH노드를 선택합니다 (예. `ETH (Etherscan.io)` 혹은 `ETH (Infura.io)` 혹은 `ETH (MyEtherWallet)`) 그리고 다시 확인합니다.',
오른쪽 상단의 목록에서 다른 ETH 노드를 선택하고

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +tx_Summary                  : '볼륨이 높은 기간(예를 들어 ICO 기간중)의 트랜잭션은 몇시간 동안 보류될 수 있습니다. 이 툴은 이러한 TX를 찾아"취소" 하거나 교체할 수 있는 기능을 제공하는 것을 목적으로 합니다. **이는 일반적으로 수행할 수 있는 작업이 아닙니다. 이를 의존하지 말아야 하며 TX풀이 가득 찼을 때만 작동합
거래량이 많은 기간
몇 시간 동안
찾아 "취소"하거나
기능 제공을 목적으로 합니다
이 툴에 의존하지 말아야 하며 TX 풀이

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +x_PasswordDesc              : '비밀번호는 개인 키를 * 암호화 * 합니다. 이것은 키를 생성할때에 씨드로 쓰이지 않습니다. **지갑을 풀기 위해서는 이 비밀번호와 개인 키 모두 필요합니다.**',
비밀번호로는 키를 생성할 수 없습니다.

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +GEN_Warning_3                   :  '**백업해두세요!** 이는 언젠가 수백만 달러의 가치를 가지게 될 수 있으니 안전하게 관리하세요.',
언젠가 수백만 달러의 가치가 될 지도 모르는 자금을 안전하게 관리하세요.

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +SEND_Helper_Contract            :  '대분의 경우 그냥 0으로 남겨두어야 합니다.',
대부분의 경우

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +ONBOARD_secure_1_content__4     :  'URL 주소창에서 `MYETHERWALLET INC` 문구가 녹색임을 확인하세요.',
녹색이 맞는지 확인하세요

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
> +HELP_14_Title               : '14) 일부 사이트에서는 마우스 이동을 통해 무작위(씨드)로 개인 키를 생성합니다. MyEtherWallet.com은 이 방식을 사용하지 않습니다. MyEtherWallet의 무작위 숫자 생성이 안전할까요? ',
'마우스를 움직여'

2018-06-01 18:08 UTC, miner7222 commented on app/scripts/translations/ko.js
>  HELP_12_Desc_6              : '"JSON 파일 다운로드 - Geth / Mist 형식 (암호화됨)" 부문을 찾아주세요. 아래의 "다운로드" 버튼을 클릭합니다. 이제 키 저장소 파일이 생겼습니다. ',
'키 저장소 -> 키스토어'
keystore를 키스토어로 번역하시는 것 같아서요.

2018-06-01 18:08 UTC, jjhitel commented on app/scripts/translations/ko.js
> +HELP_12_Desc_9              : '그러면 키 저장소 폴더가 열립니다. 방금 다운로드 한 파일 (`UTC - 2016-04-14 ........ /`)을 사용자의 키스토어 폴더에 복사합니다. ',
키 저장소 -> 키스토어
다운로드 한 -> 다운로드한

2018-06-01 18:08 UTC, jjhitel commented on app/scripts/translations/ko.js
> +HELP_16_Desc_1              : '[etherscan.io](https://etherscan.io/)와 같은 블록체인 탐색기를 사용할 수 있습니다. 주소를 검색 창에 붙여넣으면 주소와 거래 내역이 표시됩니다. 예를 들어, 우리의 [기부 계정](https://etherscan.io/address/0xDECAF9CD2367cdbb726E
우리의 [기부 계정](https~ )과 -> 저희의 [기부 계정]은 (https~)와

2018-06-01 18:08 UTC, jjhitel commented on app/scripts/translations/ko.js
> +NAV_DomainSale              : '도메인판매',
도메인 판매

2018-06-01 18:08 UTC, jjhitel commented on app/scripts/translations/ko.js
> +GAS_LIMIT_Desc              : '가스 제한은 TX와 함께 보내게 될 가스의 양입니다. `TX 수수료` = 가스 가격 * 가스 한도, 그리고 TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 이 가스량을 늘린다고 해서 TX 채굴 속도가 빨라지지는 않습니다. ETH 전송 = `21000`. 토큰 전송 = ~`200000`.'
가스 제한 -> 가스 한도

2018-06-01 18:08 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ADD_Label_1                 : '어떠한 것을 진행하시겠습니까? ',
무엇을 진행하시겠습니까?

2018-06-02 03:05 UTC, hackmod commented on app/scripts/translations/ko.js
> +x_PasswordDesc              : '비밀번호는 개인 키를 * 암호화 * 합니다. 이것은 키를 생성할때에 씨드로 쓰이지 않습니다. **지갑을 풀기 위해서는 이 비밀번호와 개인 키 모두 필요합니다.**',
비밀번호는 개인 키를 * 암호화 * 할 때 쓰이고 개인 키를 생성할 때 씨드로 쓰이지는 않습니다

2018-06-03 10:37 UTC, ghost approved these changes

2018-06-04 01:30 UTC, dakeshi reviewed
Gen Wallet update 섹션 앞부분까지 proofreading 완료.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_final_content__7        :  'MetaMask로 보내기',
Ledger, Trezor 와 동일한 문장 구조(How to Send via..)이기 때문에 통일성을 위해 아래와 같이 수정하는 것은 어떨까요?

'MetaMask에서 보내는 방법',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__5      :  'MyEtherWallet은 자유롭게 쓸 수 있는 무료의 오픈소스 클라이언트 인터페이스 입니다.',
free = 무료를 의미하기 때문에 `자유롭게 쓸 수 있는`, `무료`는 중복된 의미로 보입니다.
지난 리뷰에서 제안했던 문장을 다시 한번 검토해주시길 바랍니다.

'MyEtherWallet은 무료 오픈소스 클라이언트 인터페이스입니다.',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +x_PasswordDesc              : '비밀번호는 개인 키를 * 암호화 * 할 때 쓰이고 개인 키를 생성할 때 씨드로 쓰이지는 않습니다. **지갑을 풀기 위해서는 이 비밀번호와 개인 키 모두 필요합니다.**',
> 지갑을 풀기 위해서는

unlock 은 번역 통일성을 위해 `지갑 잠금을 해제하기 위해서는` 으로 번역하는 것이 좋겠네요.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +x_TXFee                     : 'TX 요금',
> 요금

번역 통일성을 위해 `수수료`로 변경하는 것이 좋을 듯.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_Summary                  : '거래량이 높은 기간(예를 들어 ICO 기간중)의 트랜잭션은 몇 시간 동안 보류될 수 있습니다. 이 툴은 이러한 TX를 찾아 "취소"하거나 교체할 수 있는 기능을 제공하는 것을 목적으로 합니다. **이는 일반적으로 수행할 수 있는 작업이 아닙니다. 이 툴을 의존하지 말아야 하며 TX풀이 가득 찼을 때만
> (예를 들어 ICO 기간중)

(예를 들어 ICO 기간). 중을 생략해도 충분히 의미전달 가능하다고 생각합니다.

> 이 툴은 이러한 TX를 찾아 "취소"하거나 교체할 수 있는 기능을 제공하는 것을 목적으로 합니다.

이 도구를 이용해 이러한 TX를 찾아 "취소"하거나 교체할 수 있습니다.

툴은 도구로 수정하는 것이 좋겠네요.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_notFound                 : '트랜잭션 없음',
'트랜잭션을 찾을 수 없습니다',

문맥상 검색 결과 화면일 것 같네요.

tx_notFound 
tx_foundInPending 
tx_FoundOnChain

등의 타이틀은 좀 더 친절한 문구로 제공하는 것이 좋을 것 같아 해당 타이틀도 비슷한 형태로 제안했습니다.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +NAV_CheckTxStatus           : 'TX 상태 검사',
check에 대한 번역 용어 통일이 필요해 보이네요. tx_notFound_2 에서는 '확인'이라고 번역되어 있습니다.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_notFound_3               : '여전히 다른 노드의 TX풀에서 채굴을 기다리고 있을 수 있습니다.',
> '여전히 다른 노드의 TX풀에서 채굴을 기다리고 있을 수 있습니다.',

'다른 노드의 TX풀 안에서 채굴되기를 기다리고 있는 상태일 수도 있습니다',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_notFound_4               : '오른쪽 상단에 있는 드롭 다운 목록의 다른 ETH노드를 선택합니다 (예. `ETH (Etherscan.io)` 혹은 `ETH (Infura.io)` 혹은 `ETH (MyEtherWallet)`) 그리고 다시 확인합니다.',
> 드롭 다운 목록의 

드롭 다운 목록에서

> 선택합니다...그리고 다시 확인합니다.',

선택한 다음 다시 확인해보세요.',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_foundInPending           : '보류중인 트랜잭션 발견',
'보류 중인 트랜잭션이 발견되었습니다',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_foundInPending_2         : '현재 보류중(채굴대기중). ',
'현재 보류 중(채굴되기를 기다리고 있는 중).',

채굴자가 TX 풀안에서 TX를 골라 채굴하는 것이므로 채굴되기를 기다린다는 표현이 더 적합할 것 같습니다.
https://kb.myetherwallet.com/getting-started/getting-started-new.html
채굴대기중으로 충분한 의미전달이 된다고 생각한다면 그대로 유지해도 괜찮을 듯.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_foundInPending_3         : '트랜잭션을 "취소" 하거나 바꿀 수 있는 가능성이 있습니다. 아래에 있는 지갑을 잠금 해제하세요.',
'트랜잭션을 "취소" 하거나 교체할 수 있는 기회가 있습니다.

replace는 번역 통일성을 위해 `교체`로 변경했음.

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_FoundOnChain             : '트랜잭션 발견',
'트랜잭션이 발견되었습니다',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_FoundOnChain_2           : '**만약 빨간색을 본다면 `( ! )`, 잘못된 인스트럭션 (`BAD INSTRUCTION`) 혹은 가스부족(`OUT OF GAS`) 오류 메시지**이며, 이는 트랜잭션이 성공적으로 *전송*되지 않았음을 말합니다. 이 거래는 취소하거나 대체할 수 없습니다. 대신 새 트랜잭션을 보냅니다. "가스부족"오
> '**만약 빨간색을 본다면 `( ! )`, 잘못된 인스트럭션 (`BAD INSTRUCTION`) 혹은 가스부족(`OUT OF GAS`) 오류 메시지**이며, 이는 트랜잭션이 성공적으로 *전송*되지 않았음을 말합니다.

**빨간색으로 표시된 `( ! )`, 잘못된 명령어(`BAD INSTRUCTION`) 또는 가스 부족(`OUT OF GAS`) 등의 메시지가 보인다면**, 트랜잭션이 성공적으로 *전송*되지 않은 것입니다.

  > 이 거래는 취소하거나 대체할 수 없습니다.
이 거래는 취소하거나 교체할 수 없습니다.

> "가스부족"오류가 발생한 경우 원래 지정한 가스 한도를 두배로 늘려야 합니다. ',

"가스부족" 오류가 발생한 경우 원래 지정했던 가스 한도를 두배로 늘려야 합니다. ',

2018-06-04 01:30 UTC, dakeshi commented on app/scripts/translations/ko.js
> +tx_FoundOnChain_3           : '**오류가 없으면 트랜잭션이 성공적으로 전송된 것입니다.** 전송한 ETH 혹은 토큰은 전송된 위치에 있게됩니다. ETH 또는 토큰을 다른 지갑/거래소 계좌에 입금된 것을 볼 수 없다면, 그리고 보낸 후 24시간이 지난 후라면, [서비스에 문의하세요](https://myetherwallet.githu
> '**오류가 없으면 트랜잭션이 성공적으로 전송된 것입니다.

오류 메시지가 없다면

> 전송한 ETH 혹은 토큰은 전송된 위치에 있게됩니다.
이제, ETH 또는 토큰은 당신이 전송한 곳에 있습니다.

자연스런 연결을 위해, `이제`를 추가했습니다.

> ETH 또는 토큰을 다른 지갑/거래소 계좌에 입금된 것을 볼 수 없다면, 그리고 보낸 후 24시간이 지난 후라면, [서비스에 문의하세요]

전송 후 24시간 지났어도 이 ETH 또는 토큰이 당신의 다른 지갑이나 거래소 계정에서 보이지 않는다면 [관련 서비스에 문의하시길 바랍니다.]

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +GAS_Price_3                     : '고속',
'고속'은 빠른 속도라는 한자어이므로 '빠름'과 겹칩니다. 저번에도 제안했듯 '매우 빠름' 정도가 되어야 합니다.

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__1      :  '당신의 안전을 위해서 다음 사항을 숙지해주시기 바랍니다. 🙏',
'you'를 '당신'이라는 인칭으로 계속 번역하기 보다는, '사용자' 정도로 대체하는 것이 어떨까요?

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_blockchain_content__6   :  '다시한번 말하지만: **우리는 은행이 아닙니다**.',
다시 한 번

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_content__1     :  '그들은 아무 유익 없이 돈을 요구할 것입니다.',
그들은 당신이 돈을 보내게 하고, 그 대가도 아무 것도 주지 않을 것입니다.

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_secure_2_content__2     :  '믿기지 않을 정도로, 아마도 스캠입니다.',
믿기지 않을 정도로 좋은 제안이라면, 아마도 스캠일 겁니다.

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_title          :  '캐인 키나 비밀번호를 분실하지 않는 방 ',
캐인 -> 개인
방 -> 방법

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ONBOARD_secure_3_content__4     :  'Dropbox, GoogleDrive 또는 기타 클라우드 저장소에 개인 키를 저장하지 마세요. 만약 계좌가 손상되면, 자금은 도난당할 것입니다.',
Google 드라이브

2018-06-04 05:51 UTC, jjhitel commented on app/scripts/translations/ko.js
> +ADD_MetaMask                : 'MetaMask에 연결 ',
MetaMask에 연결하기
메뉴의 다른 항목의 번역은 '연결하기'라고 되어있으므로 통일성을 위해

2018-06-04 06:18 UTC, hackmod commented on app/scripts/translations/ko.js
> +GAS_Price_3                     : '고속',
글자 수 맞추기 위해 그냥 두었는데 부자연스러운가요? 매우 빠름이 무난할 듯

2018-06-04 06:20 UTC, hackmod commented on app/scripts/translations/ko.js
> +tx_Summary                  : '거래량이 높은 기간(예를 들어 ICO 기간중)의 트랜잭션은 몇 시간 동안 보류될 수 있습니다. 이 툴은 이러한 TX를 찾아 "취소"하거나 교체할 수 있는 기능을 제공하는 것을 목적으로 합니다. **이는 일반적으로 수행할 수 있는 작업이 아닙니다. 이 툴을 의존하지 말아야 하며 TX풀이 가득 찼을 때만
일단 번역은 번역이므로 원래 의도대로 두는 것이 나을 것 같고요. 아주 부자연스럽지만 않다면 원래의 문장에서 빼는 것보다는 그대로 두는 것이 나을 것 같습니다.

2018-06-04 06:22 UTC, hackmod commented on app/scripts/translations/ko.js
> +x_PasswordDesc              : '비밀번호는 개인 키를 * 암호화 * 할 때 쓰이고 개인 키를 생성할 때 씨드로 쓰이지는 않습니다. **지갑을 풀기 위해서는 이 비밀번호와 개인 키 모두 필요합니다.**',
지갑을 푼다는 말을 꽤 흔하게 쓰기때문에 잠금 해제라는 말과 혼용해서 썼습니다.

2018-06-04 06:23 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__5      :  'MyEtherWallet은 자유롭게 쓸 수 있는 무료의 오픈소스 클라이언트 인터페이스 입니다.',
free는 분명히 무료와는 다르죠 마이이더월렛은 자유소프트웨어입니다. 단순히 무료가 아닌

2018-06-04 07:38 UTC, dakeshi commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__5      :  'MyEtherWallet은 자유롭게 쓸 수 있는 무료의 오픈소스 클라이언트 인터페이스 입니다.',
@hackmod FSF에서 주장하는 free의 의도를 담은 표현이라면 자유 오픈소스 로 표기하는게 좋겠네요.

2018-06-04 16:14 UTC, jjhitel commented on app/scripts/translations/ko.js
> +APPLE_Mob_Notice_Head       : "아이콘이나 아이패드를 사용하시는 것 같습니다.",
iPhone이나 iPad를
한국에서도 공식 표기가 이렇게 되어있어서요

2018-06-04 16:14 UTC, jjhitel commented on app/scripts/translations/ko.js
> +PHISHING_Warning_2          : '이 주소는 피싱 목록에 등록된 신고된 주소입니다. 올바른 수소로 보내는지 확인해주시기 바랍니다',
올바른 주소

2018-06-05 05:04 UTC, dakeshi reviewed
Navigation 섹션 앞 부분까지 proofreading 완료.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_1                  : '', /* FIXME */
Use your ... to access your account에서 ...에 해당하는 문맥은 다음과 같습니다.

1. hardwallet
2. keystore file

이 부분은 번역하지 않고 남겨두고 GEN_Help_2에서 처리하는 지금 구조로 유지하는게 좋겠네요.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_2                  : '을(를) 계정에 접근하기 위해 사용합니다.',
하드웨어 지갑, 키스토어 파일이 주어이므로 `(를)`은 제외해도 될 것 같네요.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_4                  : '가이드 & FAQ',
'가이드 & 자주 묻는 질문',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_5                  : '지갑 생성하기',
how to 는 ~ 방법으로 번역하고 있으므로 통일성을 위해

'지갑 생성 방법', or '지갑 만드는 방법'

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_7                  : '안전하게 보관 · 백업 하기 · 누구와도 공유하지 않기 · 잊어버리지 않기 · 잊어버리면 복구가 불가능합니다.',
> 잊어버리지 않기 · 잊어버리면 복구가 불가능합니다.',

분실하지 않기 · 분실하면 복구할 수 없습니다.

lose는 앞 부분에서 `분실`로 반영되었습니다.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_8                  : '파일을 다운로드하지 않겠습니까? ',
'파일 다운로드가 안되시나요? ',

뒤에 try using google chrome이 나오는 걸로 봐서는 다운로드가 안되는 상황을 묘사하는 것으로 보이네요.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_9                  : '구글 크롬 시도하기 ',
'구글 Chrome을 사용해보세요',

제품명이 Chrome이네요. 크롬 아님.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_12                 : 'MyEtherWallet을 통해서 지갑을 풀어냅니다. (혹은 Mist, Geth, Parity 혹은 다른 지갑 클라이언트 사용.) ',
'MyEtherWallet(또는 Mist, Geth, Parity 및 기타 지갑 클라이언트)에서 지갑 잠금을 해제할 때 이 파일을 사용하세요 ',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_13                 : '키스토어 파일을 백업하기 ',
'키스토어 파일 백업하는 방법 ',

how to 번역 통일. ~방법.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_14                 : '여러가지 다른 포맷은? ',
관련된 내용은 이곳 https://myetherwallet.github.io/knowledge-base/private-keys-passwords/difference-beween-private-key-and-keystore-file.html 인데 해당 문장은 이 주소의 콘텐츠에는 없군요. 문맥상 의역하면 아래와 같은 정도의 번역이 적합할 것 같네요.

'왜 파일 포맷들이 다른거죠? ', or '파일 포맷이 다른 이유가 뭔가요?'

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_15                 : '자금을 잃거나 혹은 도난당하는 것을 방지하기.',
'자금 도난을 막고, 키 분실을 방지하기 위해서입니다.',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_16                 : '여러가지 다른 포맷은?',
'왜 파일 포맷들이 다른거죠? ',

GEN_help 14 코멘트 참조

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_17                 : '왜 그래야 하나?',
'왜 이렇게 해야하나요?',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_18                 : '두번째 백업을 가지기.',
secondary는 두 번째가 아니라 `부수적인, 이차적인` 을 의미합니다. 의역하면 추가적인 백업 정도가 되겠네요.

'백업을 추가로 만들기 위해서입니다.',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_19                 : '비번을 잃었을 때를 대비하기.',
'비밀번호를 잊어버린 경우를 대비하기 위해서입니다.',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_20                 : '콜드 스토리지',
'콜드 스토리지(cold storage)'

https://myetherwallet.github.io/knowledge-base/offline/ethereum-cold-storage-with-myetherwallet.html

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Unlock                  : '주소를 보기 위해 지갑을 풀기',
'주소를 확인하려면 지갑을 푸세요',

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GAS_PRICE_Desc              : '가스 가격은 가스 단위당 지불할 금액입니다. `TX 수수료 = 가스 가격 * 가스 한도`, 그리고  TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 높은 가스 가격 = 트랜잭션은 빨라지나 가격은 비쌈. 기본값은 `41 GWEI`.',
> 가스 가격은 가스 단위당 지불할 금액입니다.

지불 역시 맞춤법 검사에서 '지급'으로 사용할 것을 권고하고 있습니다.

> `TX 수수료 = 가스 가격 * 가스 한도`, 그리고  TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 

`TX 수수료 = 가스 가격 * 가스 한도` 이며  TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 

> 높은 가스 가격 = 트랜잭션은 빨라지나 가격은 비쌈.

가스 가격이 높을 수록 트랜잭션은 빠르게 처리되지만, 비용이 늘어납니다.

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GAS_LIMIT_Desc              : '가스 한도는 TX와 함께 보내게 될 가스의 양입니다. `TX 수수료` = 가스 가격 * 가스 한도, 그리고 TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 이 가스량을 늘린다고 해서 TX 채굴 속도가 빨라지지는 않습니다. ETH 전송 = `21000`. 토큰 전송 = ~`200000`.'
> `TX 수수료` = 가스 가격 * 가스 한도, 그리고

`TX 수수료` = 가스 가격 * 가스 한도이며, 

> 이 가스량을 늘린다고 해서

가스 한도를 늘려도

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +NONCE_Desc                  : 'nonce는 주어진 주소에서 보낼 TX의 회수입니다. 이는 트랜잭션이 순차적으로 이루어지고 한번 이상 이루어지지 않도록 보장해줍니다.',
'nonce는 특정 주소에서 전송된 TX 횟수입니다. 이것은 트랜잭션이 순차적으로 전송되었다는 것과 두 번이상 전송되지 않았다는 것을 보장합니다.',

more than once면 두 번 이상. given은 `특정한` 으로 번역할 수 있습니다.
https://myetherwallet.github.io/knowledge-base/transactions/what-is-nonce.html

2018-06-05 05:04 UTC, dakeshi commented on app/scripts/translations/ko.js
> +TXFEE_Desc                  : 'TX 수수료는 TX를 포함한 블록을 캔 채굴자에게 지불됩니다. 이는 `가스 한도` * `가스 가격` 입니다. [GWEI단위 -> ETH단위로 변환할 수 있습니다.](https://www.myetherwallet.com/helpers.html)',
> 지불됩니다

지급합니다. 맞춤법.

2018-06-05 06:50 UTC, hackmod commented on app/scripts/translations/ko.js
> +GEN_Help_1                  : '', /* FIXME */
네 이건 일단 이렇게 해 놓고, 필요하다면 추가적으로 고치면 될 것 같습니다

2018-06-06 14:28 UTC, hackmod commented on app/scripts/translations/ko.js
> +ONBOARD_welcome_content__1      :  '당신의 안전을 위해서 다음 사항을 숙지해주시기 바랍니다. 🙏',
이 경우는 빼도 무방하므로 뺐습니다.

2018-06-06 15:03 UTC, hackmod commented on app/scripts/translations/ko.js
> +GEN_Help_14                 : '여러가지 다른 포맷은? ',
"여러 형식의 지갑들이 서로 다른 점이 뭐죠?"

"여러 지갑들의 서로 다른 점은?"

2018-06-06 15:05 UTC, hackmod commented on app/scripts/translations/ko.js
> +GEN_Help_15                 : '자금을 잃거나 혹은 도난당하는 것을 방지하기.',
자금의 도난이나 분실을 막기

2018-06-06 15:45 UTC, hackmod commented on app/scripts/translations/ko.js
> +GAS_PRICE_Desc              : '가스 가격은 가스 단위당 지불할 금액입니다. `TX 수수료 = 가스 가격 * 가스 한도`, 그리고  TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 높은 가스 가격 = 트랜잭션은 빨라지나 가격은 비쌈. 기본값은 `41 GWEI`.',
지불과 지급이 엄연히 다른 뜻 아닌가요?

원문의 표현이 좀 이상한 경우가 있는데 일단 아주 이상한 표현 아니라면 원문을 살리도록 하였습니다.

2018-06-06 16:11 UTC, hackmod commented
번역시작한지 일주일이 넘었네요. 보면 볼 수록 고칠 부분이 계속 보입니다만, 일단 freeze하는 것으로 하고  추가적 PR을 따로 열도록 하겠습니다. 수고많으셨습니다~

2018-06-06 23:37 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GAS_PRICE_Desc              : '가스 가격은 가스 단위당 지불할 금액입니다. `TX 수수료 = 가스 가격 * 가스 한도`, 그리고  TX를 포함한 블록을 채굴한 채굴자에게 수수료가 지급됩니다. 높은 가스 가격 = 트랜잭션은 빨라지나 가격은 비쌈. 기본값은 `41 GWEI`.',
아래의 사전 앱에서 `지불`에 대한 행정순화용 단어가 `지급`이라고 명시되어 있습니다. 
- 국립국어원 표준국어대사전 http://stdweb2.korean.go.kr/main.jsp
- 네이버 국어사전

2018-06-06 23:40 UTC, dakeshi commented on app/scripts/translations/ko.js
> +GEN_Help_14                 : '여러가지 다른 포맷은? ',
여러 지갑이라고 하는 것은 오해의 소지가 있을 것 같습니다.
지갑은 하나지만 백업이나 복구를 위해 사용되는 것이 private key와 keystore 방식이라는게 초점이기 때문에
이런 의미를 살리는 문장으로 번역되는게 좋을듯.

2018-06-19 04:56 UTC, ghost approved these changes

2018-06-19 16:00 UTC, merged