add akroma support
kvhnuke/etherwallet pull request #1976
Opened 2018-07-27 17:48 UTC by detroitpro

## Description

Adding support for Akroma ( akroma.io ). Akroma team is working on native oracle solutions.

- homepage: https://akroma.io
- node(s) https://rpc.akroma.io
- explorer: https://akroma.io/explorer
- BIP44/ChainId 200625 https://github.com/satoshilabs/slips/pull/326

## Trezor Support

- PR merged https://github.com/trezor/trezor-mcu/pull/387
- PR merged https://github.com/trezor/trezor-common/pull/177
- Next Trezor firmware will have full Akroma support (including EIP-155 replay protection).

2018-07-27 19:32 UTC, mkrufky reviewed
Good work.  I'm looking forward to seeing this merged.  :-)

2018-07-27 19:32 UTC, mkrufky commented on app/scripts/controllers/decryptWalletCtrl.js
> +        akromaPath:        "m/44'/200625'/0'/0",   // first address: m/44'/200625'/0'/0/0
I'm not a MEW maintainer, but I am following this effort closely and offer some feedback in an effort to speed things along.   In keeping with the existing coding style, I'd consider renaming `akromaPath` to `hwAkromaPath`

2018-07-27 19:32 UTC, mkrufky commented on app/scripts/controllers/decryptWalletCtrl.js
> +                    $scope.HDWallet.dPath = $scope.HDWallet.akromaPath;
I'd consider renaming `akromaPath` to `hwAkromaPath`

2018-07-27 19:32 UTC, mkrufky commented on app/scripts/directives/walletDecryptDrtv.html
> +                <span ng-bind="HDWallet.akromaPath"></span>
I'd consider renaming akromaPath to hwAkromaPath

2018-07-27 20:59 UTC, ghost requested changes
You should edit here also https://github.com/kvhnuke/etherwallet/pull/1976/files#diff-fdb517236c6450fac305b50634838a19R695

2018-07-27 23:00 UTC, detroitpro reviewed
Good feedback. Will rename.

2018-07-29 21:30 UTC, mkrufky commented
### Trezor Support
Chain ID > 255 support: (merged)
https://github.com/trezor/trezor-mcu/pull/381

### Ledger Support

Full 32bit Chain ID support: (merged)
https://github.com/LedgerHQ/blue-app-eth/commit/8260268b0214810872dabd154b476f5bb859aac0
https://github.com/LedgerHQ/blue-app-eth/commit/74c085ca2d032179fcf205cda1dee38c92877933

Official Ledger Akroma app: (merged)
https://github.com/LedgerHQ/blue-app-eth/pull/19

2018-07-29 21:46 UTC, mkrufky commented
One dependency remains open for Ledger support:

### MEW Support
Support 32 bit Chain ID with the latest Ledger app:
https://github.com/kvhnuke/etherwallet/pull/1979

2018-07-31 19:51 UTC, kvhnuke commented
Once @gre confirm the changes on #1979 we can merge this in as well

2018-08-01 16:23 UTC, gamalielhere approved these changes

2018-08-01 16:33 UTC, gamalielhere commented
@detroitpro can you resolve the conflict?

2018-08-01 22:03 UTC, merged