Enable Ledger Hardware Wallet support for GoChain (GO)
kvhnuke/etherwallet pull request #2057
Opened 2018-09-08 16:11 UTC by mkrufky

Ledger Nano S is now properly working with GoChain!!

homepage           : https://gochain.io
block explorer     : http://explorer.gochain.io
network statistics : http://stats.gochain.io
slip0044 index     : 6060
chainId            : 60

Ledger Nano S GoChain (GO) app: (merged)
LedgerHQ/blue-app-eth#35

cc: @gochain-io

2018-09-08 17:03 UTC, ghost requested changes

2018-09-08 17:03 UTC, eosclassicteam commented on app/scripts/controllers/decryptWalletCtrl.js
> +                case nodes.nodeTypes.GO:
We have go path for trezor already 😄

2018-09-08 19:17 UTC, mkrufky commented on app/scripts/controllers/decryptWalletCtrl.js
> +                case nodes.nodeTypes.GO:
You're right -- my mistake.  Thank you for pointing it out -- fixed.

2018-09-09 04:55 UTC, mkrufky commented
I am closing this for now -- I'll reopen it after GoChain gets on Ledger's official roadmap.

2018-09-09 04:55 UTC, closed without merging