Add EtherInc (ETI) Support
kvhnuke/etherwallet pull request #2143
Opened 2018-11-10 18:57 UTC by suryanshkumr

# Description
EtherInc is a fork of Ethereum to power the future of blockchain based organizations.

* Homepage: https://einc.io/
* Node: https://api.einc.io/jsonrpc/mainnet
* Explorer: https://explorer.einc.io/
* BIP44 / Chainid 101 ( satoshilabs/slips#438 )

# Changes
This PR adds EtherInc node support

2018-11-11 04:01 UTC, hackmod commented on app/scripts/controllers/decryptWalletCtrl.js
> +    etiPath: "m/44'/60'/0'/0", // first address: m/44'/76'/0'/0/0
wrong HD path.

2018-11-11 04:02 UTC, hackmod commented on app/scripts/directives/walletDecryptDrtv.html
> +                       value="{{HDWallet.hwIolitePath}}"/>
wrong path. it's not Iolite

2018-11-11 04:06 UTC, hackmod commented on app/styles/etherwallet-custom.less
> +  li:nth-child(33) {
wrong numbering

2018-11-11 04:12 UTC, hackmod commented
- chainId `101` - https://github.com/etherinc/go-etherinc/blob/master/params/config.go#L34
- bip44 `464` - https://github.com/satoshilabs/slips/blame/master/slip-0044.md#L495

2018-11-11 13:23 UTC, mkrufky commented
blocked by https://github.com/kvhnuke/etherwallet/issues/2145

2018-11-11 13:44 UTC, mkrufky requested changes
As described in https://github.com/kvhnuke/etherwallet/issues/2145 , both EtherInc and WebChain Networks are using Chain ID `101` , which is very problematic for user security. Given the circumstances, it is unsafe to use either of these chains without a unique chain ID for proper replay attack protection.

2018-11-11 13:44 UTC, mkrufky commented on app/scripts/controllers/decryptWalletCtrl.js
>          default:
Please link to your Ledger PR, or remove the Ledger support if it isn't actually supported.

2018-11-11 13:44 UTC, mkrufky commented on app/scripts/controllers/decryptWalletCtrl.js
>          default:
Please link to your Trezor PR, or remove the Trezor support if it isn't actually supported.

2018-11-11 13:44 UTC, mkrufky commented on app/scripts/directives/walletDecryptDrtv.html
> +           ng-show="ajaxReq.type=='ETH'||ajaxReq.type=='ETC'||ajaxReq.type=='ROPSTEN ETH'||ajaxReq.type=='RINKEBY ETH'||ajaxReq.type=='KOVAN ETH'||ajaxReq.type=='EXP'||ajaxReq.type=='UBQ'||ajaxReq.ty
Please link to your Ledger PR, or remove the Ledger support if it isn't actually supported.

2018-11-11 13:44 UTC, mkrufky commented on app/scripts/directives/walletDecryptDrtv.html
> +           ng-show="ajaxReq.type=='ETH'||ajaxReq.type=='ETC'||ajaxReq.type=='ROPSTEN ETH'||ajaxReq.type=='RINKEBY ETH'||ajaxReq.type=='KOVAN ETH'||ajaxReq.type=='EXP'||ajaxReq.type=='UBQ'||ajaxReq.ty
Please link to your Trezor PR, or remove the Trezor support if it isn't actually supported.

2018-11-12 00:07 UTC, hackmod commented
and do not insert your chain in the middle of the list. just append your network at the end.

2018-11-14 00:23 UTC, gamalielhere commented
@suryanshkumr see @mkrufky's comments. Will wait till those are resolved.

2018-12-14 00:39 UTC, tayvano commented
We appreciate you creating this pull request but upon further investigation it looks like you share a chainid with another chain (see: https://github.com/MyCryptoHQ/MyCrypto/pull/2217)

In case you don't know, if two chains have the same id, replay attacks are possible which means a user could inadvertently have their funds spent on both chains. This occurred during the ETH/ETC split and was unfortunate for all users innocently trying to move funds. 

MyCrypto prioritizes user experience and user safety and we cannot include EtherInc (or WebChain) on our platform until you have differing chainids.

We don't have the desire nor willingness to moderate a discussion between the two of you or be in the middle so I strongly recommend getting together with the WebChain team independently and figuring out a resolution. In the long run, working together to resolve this will make both of your products stronger, more secure, and show good faith towards your individual communities and the larger blockchain community. If you do not, integrations with products and exchanges will continue to be problematic.

Again, we appreciate the PR and look forward to merging you when the chainid issue is resolved. Thanks for your contributions to this space & I hope the bearish market doesn't have you or your team too down. Much love. 💖

2018-12-14 00:42 UTC, tayvano commented
Hey MEW team...just a heads up but it looks like you may have merged WebChain (which shares the same chainid as EtherInc).

We're taking the following stance on the matter for both WebChain and EtherInc and merging neither until it's resolved. Adding one and not the other is only slightly less dangerous than adding both until their chainids are different.

> We appreciate you creating this pull request but upon further investigation it looks like you share a chainid with another chain (see: https://github.com/kvhnuke/etherwallet/pull/2143)

> In case you don't know, if two chains have the same id, replay attacks are possible which means a user could inadvertently have their funds spent on both chains. This occurred during the ETH/ETC split and was unfortunate for all users innocently trying to move funds. 

> MyCrypto prioritizes user experience and user safety and we cannot include WebChain (or EtherInc) on our platform until you have differing chainids.

> We don't have the desire nor willingness to moderate a discussion between the two of you or be in the middle so I strongly recommend getting together with the EtherInc team independently and figuring out a resolution. In the long run, working together to resolve this will make both of your products stronger, more secure, and show good faith towards your individual communities and the larger blockchain community. If you do not, integrations with products and exchanges will continue to be problematic.

> Again, we appreciate the PR and look forward to merging you when the chainid issue is resolved. Thanks for your contributions to this space & I hope the bearish market doesn't have you or your team too down. Much love. 💖

2018-12-14 01:21 UTC, kvhnuke commented
Out of all possibilities, I can't believe chains are still arguing about chainIDs. We will look into this as well, thanks for notifying

2019-07-30 18:26 UTC, closed without merging